#!/bin/sh

# Set these paths appropriately

BIN="/Users/Asti/Documents/Projects/bon-prix/tag-cloud/TreeTagger/bin"
CMD="/Users/Asti/Documents/Projects/bon-prix/tag-cloud/TreeTagger/cmd"
LIB="/Users/Asti/Documents/Projects/bon-prix/tag-cloud/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/spanish-abbreviations
PARFILE=${LIB}/spanish.par
MWLFILE=${LIB}/spanish-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE
