#!/bin/sh

# Set these paths appropriately

BIN="/Users/Asti/Documents/Projects/bon-prix/tag-cloud/TreeTagger/bin"
CMD="/Users/Asti/Documents/Projects/bon-prix/tag-cloud/TreeTagger/cmd"
LIB="/Users/Asti/Documents/Projects/bon-prix/tag-cloud/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
