#!/bin/sh

# Set these paths appropriately

BIN="/Users/Asti/Documents/Projects/bon-prix/tag-cloud/TreeTagger/bin"
CMD="/Users/Asti/Documents/Projects/bon-prix/tag-cloud/TreeTagger/cmd"
LIB="/Users/Asti/Documents/Projects/bon-prix/tag-cloud/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/catalan-abbreviations
PARFILE=${LIB}/catalan.par

$TOKENIZER -c -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
