#!/bin/sh

# Set these paths appropriately

BIN="/Users/Asti/Documents/Projects/bon-prix/tag-cloud/TreeTagger/bin"
CMD="/Users/Asti/Documents/Projects/bon-prix/tag-cloud/TreeTagger/cmd"
LIB="/Users/Asti/Documents/Projects/bon-prix/tag-cloud/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

